### ISSUE TITLE
Use Symbol instead of parentProps

### ISSUE THREAD

**Issue by wuct** [Jephuff/composeNS#1]
To avoid name collision, it's better to use [`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) instead of `parentProps`.

Ref: https://github.com/acdlite/recompose/issues/358#issuecomment-293637999

**Comment by Jephuff** [comment]
I'm hesitant to remove the ability for the name spaced components to access props passed in. If there is concern that one of the namespaced components will override `parentProps`, the parent props could be pass with the key `parentProps` to be used and using Symbol for restoring?

**Comment by wuct** [comment]
I am not sure what do you mean. Using Symbol will not remove the ability for name spaced components accessing props passed in. However, I looked the code again and found out using `parentProps` doesn't cause any bug. IMO it's better to use Symbol though.

**Comment by wuct** [comment]
I will close this issue because this is not a bug.

**Comment by Jephuff** [comment]
ahh, I didn't know about `Symbol.for`. This is making a lot more sense now. I will definitely look into this.
